### ISSUE TITLE
RRTMGP shortwave radiation cache blocking code fails with blocksize > 1

### ISSUE THREAD

**Issue by pj-gdit** [ufs-community/ccpp-physics#60] opened 2023-04-03 21:23 UTC
# Description

Cache blocking code was recently added to RRTMGP radiation scheme.   The run time speedup can be dramatic when logwave blocking factor is set to a small value such as rrtmgp_lw_phys_blksz = 4.    On a small c96 test run this yields a 20% run time improvement!    

However, setting shortwave blocking to something larger than 1 results in model instability in gas_optics and cloud_optics hitting run time checks in those routines.   We believe the problem is that some MPI ranks will have daylight column counts that are not evenly mapped to the blocksize in which case some array indicies will be set to 0.   For MPI ranks that do not have this problem we see run time speedups of 15-20%.   

## Steps to Reproduce

1. set shortwave blocking factor to 4 in UFS input.nml rrtmgp_sw_phys_blksz = 4
2. Run will encounter errors like the following

 NaN in input field of mpp_reproducing_sum(_2d), this indicates numeri
cal instability

  ERROR(rrtmgp_sw_main_gas_optics):         
  gas_optics(): array tlay has values outside range
 ERROR(rrtmgp_sw_main_cloud_optics): 
 cloud optics: ice effective radius is out of bounds

## Additional Context

* WCOSS2 HPE/Cray EX
* Intel 19.1.3.304
* RRTMGP radiation scheme

**Comment by dustinswales** [comment] 2023-05-11 16:42
@pj-gdit Thanks you.
The blocking functionality is (currently) only intended to be used by the [longwave](https://github.com/ufs-community/ufs-weather-model/pull/1571) scheme in RRTMGP. I was hoping to use blocking on the shortwave as well, but as you mentioned, more work needs to be done to balance the day/night columns for this to work. 
Consequentially, the blocking for the shortwave is off in all RRTGMP supported suites by design, since we don't support this at the moment. I'm going to close this issue.

**Closed as completed by dustinswales** 2023-05-11 16:42 UTC
Labels: bug

**Comment by pj-gdit** [comment] 2023-05-16 17:11
I think it's important to tackle this at some point soon.   I've measured the performance difference in shortwave code for blocks that are complete and, for out c96 case, a sw blocking factor of 4 will yield somewhere around a 12% performance gain over a block size of 1.
